---
title: '`r format(paste(each_journal, "Monthly Report"))`'
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

this_journal <- each_journal #sets the journal for the report

no_cat_journ <- c("mBio", "MCB") #journals that don't use the category field
```

#Submissions
```{r, journ_subs_plot, fig.width= 8}
source("each_journal_monthly_report/get_journ_subs.R")

sub_trends_plot
```

```{r, journ_subs_cat, fig.length = 12, fig.width=8}
source("each_journal_monthly_report/get_journ_subs.R")

plot_YTD_subs
```

#Transfers
```{r, recent_transfers}
source("each_journal_monthly_report/get_transfers.R")

knitr::kable(J_recent_transfers, format = "html", digits = 2,  col.names = c("Date", "From", "Manuscript Number", "Title", "Editor", "Decision")) %>%
  footnote(general = "Transfers received in the last month") %>% 
  kable_styling()

knitr::kable(J_transfers_ytd, format = "html", digits = 2,  col.names = c("Decision", "N", "Percent")) %>%
  footnote(general = "Final outcomes on transfers recieved in the last 12 months") %>% 
  kable_styling()
```

#Useage Stats
```{r, journ_usage_barplot, fig.width= 8}
source("each_journal_monthly_report/get_journ_usage.R")

total_views
date_views
cat_views
```

#10 most-frequently read articles
```{r, top_10_read}
source("each_journal_monthly_report/get_top_10_read.R")

knitr::kable(top_summary, format = "html", digits = 2,  col.names = c("Editor", "DOI", "Publication Date", "Manuscript Type", "Category", "Total Reads")) %>%
  footnote(general = "Selected from articles published in the last 12 months, ranked on HighWire html & pdf views") %>% 
  kable_styling()
```

#Citations by category
```{r, journ_cites_category, fig.width= 8}
source("each_journal_monthly_report/get_journ_cites.R")

total_cites
each_cite
```

#10 most-frequently cited articles
```{r, top_10_cited}
source("each_journal_monthly_report/get_top_10_cited.R")

knitr::kable(top_cited_summary, format = "html", digits = 2,  col.names = c("Editor", "DOI", "Publication Date", "Manuscript Type", "Category", "Total Cites")) %>%
  footnote(general = "Selected from articles published in the last 12 months") %>% 
  kable_styling()
```


#Acceptance and rejection rates by article type
```{r, editor_manu_type}
source("each_journal_monthly_report/get_editor_manu_type.R")

knitr::kable(article_summary, format = "html", digits = 2,  col.names = c("Manuscript Type", "Decision", "N", "%")) %>%  
  collapse_rows(1) %>% 
  footnote(general = "Includes all submissions YTD") %>% 
  kable_styling()
```


#Number of original manuscripts assigned to editors
```{r editor_assign}
source("each_journal_monthly_report/get_editor_assign.R") 

knitr::kable(editor_assign_all_summary, format = "html", digits = 2) %>% 
  footnote(general = "Manuscripts assigned to each editor for the YTD") %>% 
  kable_styling()
```

#Days to first decision by editor
```{r, editor_dec}
source("each_journal_monthly_report/get_editor_desc_days.R") 

knitr::kable(editor_desc_year_sums, format = "html", digits = 2,  col.names = c("Editor", "N", "Average", "Median", "Minimum", "Maximum")) %>%
  footnote(general = "Includes decisions made following peer review on initial submissions in the last 12 months") %>% 
  kable_styling()
```


#Acceptance and rejection rates by editor
```{r, editor_acc_rej}
source("each_journal_monthly_report/get_editor_acc_rej_rates.R") 

knitr::kable(editor_acc_rej_summary, format = "html", digits = 2,  col.names = c("Editor", "N", "%", "N", "%", "N", "%")) %>% 
  add_header_above(c(" ", "Editorial Rejections" = 2, "Rejected" = 2, "Accepted" = 2)) %>% 
  footnote(general = "Includes all decisions made in the last 12 months") %>% 
  kable_styling()
```


#Problem manuscript report
```{r, problem_manus}
source("each_journal_monthly_report/get_problem_manus.R")

knitr::kable(problem_data, format = "html", digits = 2,  col.names = c("Manuscript Number", "Editor", "Recieved Date", "Decision Date", "Days Since Decision", "Status")) %>%
  kable_styling()
```

